import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

export type Language = "en" | "fr" | "ar";

const STORAGE_KEY = "jadisart:language";

const translations = {
  en: {
    "nav.home": "Home", "nav.marketplace": "Marketplace", "nav.categories": "Categories", "nav.about": "About", "nav.contact": "Contact", "nav.support": "Customer service", "nav.dashboard": "Dashboard", "nav.account": "Account",
    "a11y.account": "Sign in or view account", "a11y.cart": "Shopping cart", "a11y.menu": "Toggle navigation", "a11y.language": "Choose language", "auth.signOut": "Sign out",
    "home.eyebrow": "Established for the long-lived", "home.title.before": "Objects that have already", "home.title.gold": "outlived a century", "home.intro": "JadisArt brings together antiques, vintage design and historical curiosities from trusted European dealers — each authenticated, documented and ready for its next chapter.", "home.browse": "Browse the collection", "home.story": "Our story", "home.piecesPlaced": "Pieces placed", "home.dealers": "Partner dealers", "home.authenticated": "Authenticated",
    "home.featuredEyebrow": "Currently on view", "home.featured": "Featured antiques", "home.viewAll": "View all pieces", "home.categoriesEyebrow": "Explore by discipline", "home.categories": "Categories", "home.categoriesIntro": "Discover objects with history, curated across ten specialist collections.", "home.exploreCategory": "Explore collection",
    "home.standard": "The JadisArt standard", "home.why": "Why choose JadisArt", "home.aboutEyebrow": "About the company", "home.aboutTitle": "A dealer’s eye, a collector’s patience", "home.readStory": "Read our story", "home.specialist": "Speak with a specialist", "home.testimonialsEyebrow": "Collectors on JadisArt", "home.testimonials": "Trusted by careful buyers",
    "market.eyebrow": "The catalogue", "market.title": "Marketplace", "market.intro": "authenticated pieces, selected by our specialists. Search instantly, filter by material or price, and sort to taste.", "market.filters": "Filters", "market.category": "Category", "market.allCategories": "All categories", "market.material": "Material", "market.allMaterials": "All materials", "market.maxPrice": "Max price", "market.reset": "Reset filters", "market.search": "Search antiques", "market.searchPlaceholder": "Search by title, material or description…", "market.sort": "Sort by", "market.newest": "Newest first", "market.oldest": "Oldest first", "market.priceAsc": "Price: low to high", "market.priceDesc": "Price: high to low", "market.piece": "piece", "market.pieces": "pieces", "market.found": "found", "market.empty": "Nothing matches that search", "market.emptyHint": "Try widening the price range or clearing the filters.", "market.previous": "Previous", "market.next": "Next",
    "product.material": "Material", "product.size": "Size", "product.weight": "Weight", "product.view": "View details", "product.add": "Add to cart", "product.added": "added to your cart", "product.unavailable": "This piece is no longer available", "product.unavailableHint": "It may have found a new home. Browse the rest of the collection.", "product.back": "Back to marketplace", "product.category": "Category", "product.year": "Year", "product.condition": "Condition", "product.availability": "Availability", "product.inStock": "in stock", "product.seller": "Seller", "product.verified": "Verified dealer. Condition report and provenance documentation supplied with every purchase.", "product.contactSeller": "Contact seller", "product.contactTitle": "Contact the seller", "product.contactDescription": "Your message about this piece goes straight to the JadisArt team.", "product.sent": "Message sent — a specialist will reply within one business day.",
    "newsletter.eyebrow": "The Collector’s Letter", "newsletter.title": "First look at every new acquisition", "newsletter.body": "One considered email each month: newly authenticated pieces, private viewings and notes from our restorers.", "newsletter.email": "Email address", "newsletter.join": "Subscribe", "newsletter.joining": "Joining…",
    "footer.about": "A curated marketplace for antiques, vintage design, collectibles and objects with a history worth keeping.", "footer.explore": "Explore", "footer.aboutLink": "About JadisArt", "footer.contact": "Contact & FAQ", "footer.cart": "Shopping cart", "footer.categories": "Categories", "footer.gallery": "Gallery", "footer.rights": "All rights reserved.",
    "about.eyebrow": "About the company", "about.intro": "JadisArt exists because good objects deserve accurate descriptions, and collectors deserve to know exactly what they are buying.",
    "about.storyEyebrow": "Our story", "about.storyTitle": "From workshop to marketplace", "about.story1": "The company started as a restoration workshop in the Marais: three benches, a fume cupboard and an unreasonable number of varnish samples. Clients kept asking where they could find pieces of the same calibre, and the honest answer was that most of the market was opaque.", "about.story2": "So we built the marketplace we wanted to buy from. Every object is inspected in person, dated, photographed under consistent light, and listed with a condition report that hides nothing. Today JadisArt places furniture, paintings, jewelry, coins, ceramics and curiosities into collections across thirty countries.", "about.storyCta": "See what is available now", "about.storyImageAlt": "A neoclassical marble bust in the JadisArt studio",
    "about.missionTitle": "Our mission", "about.mission": "To make buying an antique as clear and confident as buying anything else: accurate descriptions, verified provenance, fair prices and specialists who answer the phone.", "about.visionTitle": "Our vision", "about.vision": "A market where historical objects circulate responsibly — properly researched, properly restored, and passed on in better condition than we found them.",
    "about.valuesEyebrow": "What we hold to", "about.valuesTitle": "Our values", "about.value1.title": "Honesty over polish", "about.value1.body": "We photograph the chips as carefully as the gilding. Condition reports name every repair.", "about.value2.title": "Scholarship", "about.value2.body": "Attribution is research, not guesswork. If we cannot prove it, we say so plainly.", "about.value3.title": "Stewardship", "about.value3.body": "We sell to people who will care for a piece, and we help them do it properly.", "about.value4.title": "Fair dealing", "about.value4.body": "Transparent pricing for buyers, fair terms for the dealers and makers we work with.",
    "about.trustEyebrow": "Peace of mind", "about.trustTitle": "Why customers trust JadisArt", "about.trust1": "Independent authentication on every piece before listing", "about.trust2": "Written condition report and provenance file with each sale", "about.trust3": "14-day return window on any item that differs from its description", "about.trust4": "Insured, fine-art crated delivery worldwide", "about.trust5": "Specialists available by phone, email or private appointment", "about.talk": "Talk to a specialist",
    "account.label": "My account", "account.logout": "Log out", "account.profile": "Profile", "account.orders": "Orders", "account.cart": "Cart", "account.wishlist": "Wishlist", "account.messages": "Messages", "account.profileInfo": "Profile information", "account.firstName": "First name", "account.lastName": "Last name", "account.phone": "Phone number", "account.saving": "Saving…", "account.save": "Save changes", "account.updated": "Profile updated.", "account.saveError": "Your profile could not be saved.", "account.noOrder": "You have not placed an order yet.", "account.emptyCart": "Your cart is empty.", "account.emptyWishlist": "Your wishlist is empty. Use the heart on a piece to save it.", "account.remove": "Remove", "account.total": "Total", "account.checkout": "Checkout", "account.order": "Order", "account.browse": "Browse the collection",
    "auth.account": "JadisArt account", "auth.welcome": "Welcome", "auth.intro": "Follow your orders, wishlist and conversations with our specialists.", "auth.signIn": "Sign in", "auth.create": "Create account", "auth.google": "Continue with Google", "auth.connecting": "Connecting…", "auth.or": "or", "auth.password": "Password", "auth.signingIn": "Signing in…", "auth.createMy": "Create my account", "auth.creating": "Creating account…", "auth.help": "Need help?", "auth.chat": "Chat with customer service", "auth.googleError": "Google sign-in failed. Please try again.", "auth.welcomeBack": "Welcome back to JadisArt.", "auth.ready": "Your JadisArt account is ready.", "auth.confirmEmail": "Check your inbox to confirm your email address.", "validation.firstName": "Please enter your first name", "validation.lastName": "Please enter your last name", "validation.email": "Please enter a valid email address", "validation.phone": "Please enter your phone number", "validation.password": "Use at least 8 characters",
    "cart.title": "Shopping cart", "cart.empty": "Your cart is currently empty.", "cart.reserved": "item reserved for you.", "cart.reservedPlural": "items reserved for you.", "cart.nothing": "Nothing here yet — browse the collection to find your next piece.", "cart.continue": "Continue shopping", "cart.decrease": "Decrease quantity", "cart.increase": "Increase quantity", "cart.remove": "Remove", "cart.summary": "Order summary", "cart.subtotal": "Subtotal", "cart.shipping": "Shipping", "cart.shippingQuote": "Quoted after checkout", "cart.proceed": "Proceed to checkout",
    "categories.eyebrow": "Collections", "categories.title": "Browse by category", "categories.intro": "Each category is curated and authenticated by our specialists, from 18th-century cabinetry to rare timepieces.", "categories.available": "available", "categories.piece": "piece", "categories.pieces": "pieces",
    "checkout.title": "Checkout", "checkout.empty": "Your cart is empty.", "checkout.signIn": "Sign in or create an account", "checkout.signInHint": "to confirm your order and follow its progress.", "checkout.delivery": "Delivery details", "checkout.fullName": "Full name", "checkout.address": "Address", "checkout.city": "City", "checkout.postal": "Postal code", "checkout.country": "Country", "checkout.confirming": "Confirming…", "checkout.confirm": "Confirm order", "checkout.payment": "No payment is taken online. Our team contacts you with a secure payment link and a shipping quote.", "checkout.quantity": "Quantity", "checkout.confirmed": "Order confirmed — our team will contact you about delivery.", "checkout.signInRequired": "Please sign in to confirm your order.", "checkout.correctFields": "Please correct the highlighted fields.", "checkout.orderError": "We could not place your order. Please try again.", "checkout.itemsError": "Your order was created but the items could not be saved. Please contact us.",
    "contact.eyebrow": "Get in touch", "contact.title": "Contact the JadisArt gallery", "contact.intro": "A question about a piece, a valuation, a delivery? Our specialists answer every message personally.", "contact.email": "Email", "contact.phone": "Phone", "contact.address": "Address", "contact.hours": "Opening hours", "contact.send": "Send us a message", "contact.subject": "Subject", "contact.message": "Message", "contact.sending": "Sending…", "contact.sendButton": "Send message", "contact.inbox": "Your message is delivered to the JadisArt inbox", "contact.help": "Need help?", "contact.helpIntro": "Our JadisArt team is available to answer your questions.", "contact.contactUs": "Contact us", "contact.chat": "Chat with customer service", "contact.faq": "Frequent questions", "contact.sent": "Message sent — our team replies within one working day.", "contact.sendError": "Your message could not be sent. Please try again.",
    "dashboard.seller": "Seller area", "dashboard.title": "Publish an antique", "dashboard.deniedTitle": "Seller dashboard", "dashboard.denied": "This area is reserved for JadisArt sellers. Contact us if you would like to list pieces with us.", "dashboard.contact": "Contact JadisArt", "dashboard.productTitle": "Product title *", "dashboard.description": "Description *", "dashboard.images": "Image URLs (one per line)", "dashboard.price": "Price (EUR)", "dashboard.stock": "Stock quantity", "dashboard.condition": "Condition", "dashboard.sellerName": "Seller name", "dashboard.location": "Seller location", "dashboard.publishing": "Publishing…", "dashboard.publish": "Publish to marketplace", "dashboard.live": "Live listings", "dashboard.published": "Listing published to the marketplace.", "dashboard.publishError": "The listing could not be published.",
    "support.eyebrow": "Customer service", "support.title": "Need help?", "support.intro": "Our JadisArt team is available to answer questions about a piece, delivery, valuation or current order.", "support.email": "Contact us by email", "support.contactForm": "Contact form", "chat.online": "Online", "chat.welcome": "Hello and welcome to JadisArt. Ask us your question and our team will reply quickly.", "chat.you": "You", "chat.placeholder": "Write your message…", "chat.send": "Send", "chat.login": "Sign in", "chat.history": "to keep your conversation history.", "chat.open": "Open customer service chat", "chat.close": "Close chat", "newsletter.error": "We could not save your subscription. Please try again.", "newsletter.success": "Welcome to the JadisArt circle — new arrivals land in your inbox first.",
    "common.pageNotFound": "Page not found", "common.pageMissing": "The page you're looking for doesn't exist or has been moved.", "common.goHome": "Go home", "common.pageError": "This page didn't load", "common.pageErrorHint": "Something went wrong on our end. You can try refreshing or head back home.", "common.tryAgain": "Try again", "faq.1q": "How do you authenticate the pieces you sell?", "faq.1a": "Every object is examined by our in-house specialists and, when relevant, by an external expert. A condition report and provenance note travel with each purchase.", "faq.2q": "Do you ship internationally?", "faq.2a": "Yes. We work with fine-art couriers and ship worldwide with museum-grade crating and full insurance.", "faq.3q": "Can I return an item?", "faq.3a": "You may return any piece within 14 days of delivery if it does not match its description. Items must be returned in their original crating.", "faq.4q": "Do you buy or take antiques on consignment?", "faq.4a": "We do. Send photographs, dimensions and any provenance you have through the form and our acquisitions team will reply within two working days.",
  },
  fr: {
    "nav.home": "Accueil", "nav.marketplace": "Galerie", "nav.categories": "Catégories", "nav.about": "À propos", "nav.contact": "Contact", "nav.support": "Service client", "nav.dashboard": "Tableau de bord", "nav.account": "Mon compte",
    "a11y.account": "Se connecter ou voir le compte", "a11y.cart": "Panier", "a11y.menu": "Ouvrir la navigation", "a11y.language": "Choisir la langue", "auth.signOut": "Se déconnecter",
    "home.eyebrow": "Créé pour traverser le temps", "home.title.before": "Des objets qui ont déjà", "home.title.gold": "traversé un siècle", "home.intro": "JadisArt réunit antiquités, design vintage et curiosités historiques de marchands européens de confiance — chaque pièce est authentifiée, documentée et prête pour son prochain chapitre.", "home.browse": "Découvrir la collection", "home.story": "Notre histoire", "home.piecesPlaced": "Pièces confiées", "home.dealers": "Marchands partenaires", "home.authenticated": "Authentifiées",
    "home.featuredEyebrow": "Actuellement exposées", "home.featured": "Antiquités à la une", "home.viewAll": "Voir toutes les pièces", "home.categoriesEyebrow": "Explorer par discipline", "home.categories": "Catégories", "home.categoriesIntro": "Découvrez des objets chargés d’histoire, réunis dans dix collections spécialisées.", "home.exploreCategory": "Explorer la collection",
    "home.standard": "L’exigence JadisArt", "home.why": "Pourquoi choisir JadisArt", "home.aboutEyebrow": "À propos de la maison", "home.aboutTitle": "L’œil d’un marchand, la patience d’un collectionneur", "home.readStory": "Lire notre histoire", "home.specialist": "Parler à un spécialiste", "home.testimonialsEyebrow": "Les collectionneurs témoignent", "home.testimonials": "La confiance des connaisseurs",
    "market.eyebrow": "Le catalogue", "market.title": "Galerie", "market.intro": "pièces authentifiées, sélectionnées par nos spécialistes. Recherchez instantanément et filtrez par matière ou prix.", "market.filters": "Filtres", "market.category": "Catégorie", "market.allCategories": "Toutes les catégories", "market.material": "Matière", "market.allMaterials": "Toutes les matières", "market.maxPrice": "Prix maximum", "market.reset": "Réinitialiser", "market.search": "Rechercher des antiquités", "market.searchPlaceholder": "Rechercher par titre, matière ou description…", "market.sort": "Trier par", "market.newest": "Plus récentes", "market.oldest": "Plus anciennes", "market.priceAsc": "Prix croissant", "market.priceDesc": "Prix décroissant", "market.piece": "pièce", "market.pieces": "pièces", "market.found": "trouvées", "market.empty": "Aucun résultat", "market.emptyHint": "Élargissez la plage de prix ou réinitialisez les filtres.", "market.previous": "Précédent", "market.next": "Suivant",
    "product.material": "Matière", "product.size": "Dimensions", "product.weight": "Poids", "product.view": "Voir le détail", "product.add": "Ajouter au panier", "product.added": "ajouté au panier", "product.unavailable": "Cette pièce n’est plus disponible", "product.unavailableHint": "Elle a peut-être trouvé un nouveau foyer. Découvrez le reste de la collection.", "product.back": "Retour à la galerie", "product.category": "Catégorie", "product.year": "Année", "product.condition": "État", "product.availability": "Disponibilité", "product.inStock": "en stock", "product.seller": "Vendeur", "product.verified": "Marchand vérifié. Rapport d’état et dossier de provenance fournis avec chaque achat.", "product.contactSeller": "Contacter le vendeur", "product.contactTitle": "Contacter le vendeur", "product.contactDescription": "Votre message au sujet de cette pièce est transmis directement à l’équipe JadisArt.", "product.sent": "Message envoyé — un spécialiste vous répondra sous un jour ouvré.",
    "newsletter.eyebrow": "La Lettre du Collectionneur", "newsletter.title": "Découvrez chaque nouvelle acquisition en avant-première", "newsletter.body": "Un message choisi chaque mois : nouvelles pièces authentifiées, visites privées et notes de nos restaurateurs.", "newsletter.email": "Adresse e-mail", "newsletter.join": "S’abonner", "newsletter.joining": "Inscription…",
    "footer.about": "Une galerie d’antiquités, de design vintage et d’objets de collection dont l’histoire mérite d’être préservée.", "footer.explore": "Explorer", "footer.aboutLink": "À propos de JadisArt", "footer.contact": "Contact et FAQ", "footer.cart": "Panier", "footer.categories": "Catégories", "footer.gallery": "Galerie", "footer.rights": "Tous droits réservés.",
    "about.eyebrow": "À propos de la maison", "about.intro": "JadisArt existe parce que les belles pièces méritent des descriptions exactes, et que les collectionneurs méritent de savoir précisément ce qu’ils achètent.",
    "about.storyEyebrow": "Notre histoire", "about.storyTitle": "De l’atelier à la galerie", "about.story1": "La maison est née d’un atelier de restauration dans le Marais : trois établis, une hotte aspirante et un nombre déraisonnable d’échantillons de vernis. Nos clients demandaient sans cesse où trouver des pièces du même calibre ; la réponse honnête était que le marché restait opaque.", "about.story2": "Nous avons donc créé la galerie où nous aurions aimé acheter. Chaque objet est examiné en personne, daté, photographié sous une lumière constante et présenté avec un rapport d’état qui ne cache rien. Aujourd’hui, JadisArt place mobilier, peintures, bijoux, monnaies, céramiques et curiosités dans des collections de trente pays.", "about.storyCta": "Voir les pièces disponibles", "about.storyImageAlt": "Un buste néoclassique en marbre dans l’atelier JadisArt",
    "about.missionTitle": "Notre mission", "about.mission": "Rendre l’achat d’une antiquité aussi clair et serein que n’importe quel autre achat : descriptions exactes, provenance vérifiée, prix justes et spécialistes joignables.", "about.visionTitle": "Notre vision", "about.vision": "Un marché où les objets historiques circulent de manière responsable — bien étudiés, bien restaurés et transmis en meilleur état que nous les avons trouvés.",
    "about.valuesEyebrow": "Ce qui nous guide", "about.valuesTitle": "Nos valeurs", "about.value1.title": "L’honnêteté avant le brillant", "about.value1.body": "Nous photographions les éclats avec autant de soin que les dorures. Chaque restauration est mentionnée.", "about.value2.title": "Recherche", "about.value2.body": "Une attribution se démontre, elle ne se devine pas. Si nous ne pouvons le prouver, nous le disons.", "about.value3.title": "Transmission", "about.value3.body": "Nous vendons à celles et ceux qui prendront soin d’une pièce, et nous les y aidons.", "about.value4.title": "Loyauté commerciale", "about.value4.body": "Des prix transparents pour les acheteurs, des conditions justes pour nos marchands partenaires.",
    "about.trustEyebrow": "Sérénité", "about.trustTitle": "Pourquoi nos clients nous font confiance", "about.trust1": "Authentification indépendante de chaque pièce avant sa mise en ligne", "about.trust2": "Rapport d’état écrit et dossier de provenance pour chaque vente", "about.trust3": "Retour sous 14 jours pour toute pièce non conforme à sa description", "about.trust4": "Livraison mondiale assurée en caisse pour œuvres d’art", "about.trust5": "Spécialistes disponibles par téléphone, e-mail ou sur rendez-vous privé", "about.talk": "Parler à un spécialiste",
    "account.label": "Mon compte", "account.logout": "Se déconnecter", "account.profile": "Profil", "account.orders": "Commandes", "account.cart": "Panier", "account.wishlist": "Favoris", "account.messages": "Messages", "account.profileInfo": "Informations du profil", "account.firstName": "Prénom", "account.lastName": "Nom", "account.phone": "Téléphone", "account.saving": "Enregistrement…", "account.save": "Enregistrer", "account.updated": "Profil mis à jour.", "account.saveError": "Votre profil n’a pas pu être enregistré.", "account.noOrder": "Vous n’avez pas encore passé de commande.", "account.emptyCart": "Votre panier est vide.", "account.emptyWishlist": "Votre liste de favoris est vide. Utilisez le cœur d’une pièce pour la sauvegarder.", "account.remove": "Retirer", "account.total": "Total", "account.checkout": "Commander", "account.order": "Commande", "account.browse": "Découvrir la collection",
    "auth.account": "Compte JadisArt", "auth.welcome": "Bienvenue", "auth.intro": "Suivez vos commandes, vos favoris et vos échanges avec nos spécialistes.", "auth.signIn": "Se connecter", "auth.create": "Créer un compte", "auth.google": "Continuer avec Google", "auth.connecting": "Connexion…", "auth.or": "ou", "auth.password": "Mot de passe", "auth.signingIn": "Connexion…", "auth.createMy": "Créer mon compte", "auth.creating": "Création du compte…", "auth.help": "Besoin d’aide ?", "auth.chat": "Discuter avec le service client", "auth.googleError": "La connexion Google a échoué. Veuillez réessayer.", "auth.welcomeBack": "Bon retour chez JadisArt.", "auth.ready": "Votre compte JadisArt est prêt.", "auth.confirmEmail": "Consultez votre boîte mail pour confirmer votre adresse.", "validation.firstName": "Saisissez votre prénom", "validation.lastName": "Saisissez votre nom", "validation.email": "Saisissez une adresse e-mail valide", "validation.phone": "Saisissez votre numéro de téléphone", "validation.password": "Utilisez au moins 8 caractères",
    "cart.title": "Panier", "cart.empty": "Votre panier est actuellement vide.", "cart.reserved": "article réservé pour vous.", "cart.reservedPlural": "articles réservés pour vous.", "cart.nothing": "Rien ici pour le moment — découvrez la collection pour trouver votre prochaine pièce.", "cart.continue": "Continuer mes achats", "cart.decrease": "Diminuer la quantité", "cart.increase": "Augmenter la quantité", "cart.remove": "Retirer", "cart.summary": "Récapitulatif", "cart.subtotal": "Sous-total", "cart.shipping": "Livraison", "cart.shippingQuote": "Devis après la commande", "cart.proceed": "Passer la commande",
    "categories.eyebrow": "Collections", "categories.title": "Parcourir par catégorie", "categories.intro": "Chaque catégorie est sélectionnée et authentifiée par nos spécialistes, de l’ébénisterie du XVIIIe siècle aux garde-temps rares.", "categories.available": "disponibles", "categories.piece": "pièce", "categories.pieces": "pièces",
    "checkout.title": "Commande", "checkout.empty": "Votre panier est vide.", "checkout.signIn": "Se connecter ou créer un compte", "checkout.signInHint": "pour confirmer votre commande et suivre son avancement.", "checkout.delivery": "Détails de livraison", "checkout.fullName": "Nom complet", "checkout.address": "Adresse", "checkout.city": "Ville", "checkout.postal": "Code postal", "checkout.country": "Pays", "checkout.confirming": "Confirmation…", "checkout.confirm": "Confirmer la commande", "checkout.payment": "Aucun paiement n’est prélevé en ligne. Notre équipe vous contactera avec un lien de paiement sécurisé et un devis de livraison.", "checkout.quantity": "Quantité", "checkout.confirmed": "Commande confirmée — notre équipe vous contactera au sujet de la livraison.", "checkout.signInRequired": "Connectez-vous pour confirmer votre commande.", "checkout.correctFields": "Corrigez les champs indiqués.", "checkout.orderError": "Nous n’avons pas pu enregistrer votre commande. Veuillez réessayer.", "checkout.itemsError": "Votre commande a été créée mais ses articles n’ont pas pu être enregistrés. Contactez-nous.",
    "contact.eyebrow": "Contactez-nous", "contact.title": "Contacter la galerie JadisArt", "contact.intro": "Une question sur une pièce, une estimation ou une livraison ? Nos spécialistes répondent personnellement à chaque message.", "contact.email": "E-mail", "contact.phone": "Téléphone", "contact.address": "Adresse", "contact.hours": "Horaires d’ouverture", "contact.send": "Écrivez-nous", "contact.subject": "Objet", "contact.message": "Message", "contact.sending": "Envoi…", "contact.sendButton": "Envoyer le message", "contact.inbox": "Votre message est envoyé à la boîte JadisArt", "contact.help": "Besoin d’aide ?", "contact.helpIntro": "Notre équipe JadisArt est à votre disposition pour répondre à vos questions.", "contact.contactUs": "Contactez-nous", "contact.chat": "Discuter avec le service client", "contact.faq": "Questions fréquentes", "contact.sent": "Message envoyé — notre équipe répond sous un jour ouvré.", "contact.sendError": "Votre message n’a pas pu être envoyé. Veuillez réessayer.",
    "dashboard.seller": "Espace vendeur", "dashboard.title": "Publier une antiquité", "dashboard.deniedTitle": "Tableau de bord vendeur", "dashboard.denied": "Cet espace est réservé aux vendeurs JadisArt. Contactez-nous si vous souhaitez proposer des pièces.", "dashboard.contact": "Contacter JadisArt", "dashboard.productTitle": "Titre de la pièce *", "dashboard.description": "Description *", "dashboard.images": "URL des images (une par ligne)", "dashboard.price": "Prix (EUR)", "dashboard.stock": "Quantité disponible", "dashboard.condition": "État", "dashboard.sellerName": "Nom du vendeur", "dashboard.location": "Lieu du vendeur", "dashboard.publishing": "Publication…", "dashboard.publish": "Publier dans la galerie", "dashboard.live": "Annonces en ligne", "dashboard.published": "Annonce publiée dans la galerie.", "dashboard.publishError": "L’annonce n’a pas pu être publiée.",
    "support.eyebrow": "Service client", "support.title": "Besoin d’aide ?", "support.intro": "Notre équipe JadisArt répond à vos questions sur une pièce, une livraison, une estimation ou une commande en cours.", "support.email": "Nous contacter par e-mail", "support.contactForm": "Formulaire de contact", "chat.online": "En ligne", "chat.welcome": "Bonjour et bienvenue chez JadisArt. Posez votre question, notre équipe vous répond rapidement.", "chat.you": "Vous", "chat.placeholder": "Écrivez votre message…", "chat.send": "Envoyer", "chat.login": "Connectez-vous", "chat.history": "pour conserver l’historique de vos conversations.", "chat.open": "Ouvrir le chat du service client", "chat.close": "Fermer le chat", "newsletter.error": "Nous n’avons pas pu enregistrer votre inscription. Veuillez réessayer.", "newsletter.success": "Bienvenue dans le cercle JadisArt — les nouveautés arrivent en avant-première dans votre boîte mail.",
    "common.pageNotFound": "Page introuvable", "common.pageMissing": "La page que vous cherchez n’existe pas ou a été déplacée.", "common.goHome": "Accueil", "common.pageError": "Cette page n’a pas pu se charger", "common.pageErrorHint": "Un problème est survenu. Vous pouvez actualiser la page ou revenir à l’accueil.", "common.tryAgain": "Réessayer", "faq.1q": "Comment authentifiez-vous les pièces vendues ?", "faq.1a": "Chaque objet est examiné par nos spécialistes et, si nécessaire, par un expert extérieur. Un rapport d’état et une note de provenance accompagnent chaque achat.", "faq.2q": "Expédiez-vous à l’international ?", "faq.2a": "Oui. Nous travaillons avec des transporteurs d’œuvres d’art et expédions dans le monde entier, avec caisse de qualité muséale et assurance complète.", "faq.3q": "Puis-je retourner un article ?", "faq.3a": "Vous pouvez retourner toute pièce sous 14 jours si elle ne correspond pas à sa description. Les articles doivent être renvoyés dans leur caisse d’origine.", "faq.4q": "Achetez-vous des antiquités ou acceptez-vous les dépôts-ventes ?", "faq.4a": "Oui. Envoyez-nous photos, dimensions et documents de provenance via le formulaire ; notre équipe acquisitions répondra sous deux jours ouvrés.",
  },
  ar: {
    "nav.home": "الرئيسية", "nav.marketplace": "المعرض", "nav.categories": "الفئات", "nav.about": "من نحن", "nav.contact": "اتصل بنا", "nav.support": "خدمة العملاء", "nav.dashboard": "لوحة التحكم", "nav.account": "حسابي",
    "a11y.account": "تسجيل الدخول أو عرض الحساب", "a11y.cart": "سلة التسوق", "a11y.menu": "فتح قائمة التنقل", "a11y.language": "اختيار اللغة", "auth.signOut": "تسجيل الخروج",
    "home.eyebrow": "قطع خُلقت لتدوم", "home.title.before": "قطع فنية عاشت بالفعل", "home.title.gold": "أكثر من قرن", "home.intro": "تجمع جاديس آرت التحف والتصاميم العتيقة والنوادر التاريخية من تجار أوروبيين موثوقين — كل قطعة موثقة ومصادق عليها وجاهزة لفصلها الجديد.", "home.browse": "اكتشف المجموعة", "home.story": "قصتنا", "home.piecesPlaced": "قطعة مقتناة", "home.dealers": "تاجراً شريكاً", "home.authenticated": "موثقة",
    "home.featuredEyebrow": "معروضة حالياً", "home.featured": "تحف مختارة", "home.viewAll": "عرض كل القطع", "home.categoriesEyebrow": "استكشف حسب التخصص", "home.categories": "الفئات", "home.categoriesIntro": "اكتشف قطعاً تحمل تاريخاً عريقاً ضمن عشر مجموعات متخصصة.", "home.exploreCategory": "استكشف المجموعة",
    "home.standard": "معايير جاديس آرت", "home.why": "لماذا تختار جاديس آرت", "home.aboutEyebrow": "عن الدار", "home.aboutTitle": "عين الخبير وصبر جامع التحف", "home.readStory": "اقرأ قصتنا", "home.specialist": "تحدث مع خبير", "home.testimonialsEyebrow": "آراء جامعي التحف", "home.testimonials": "ثقة أهل الخبرة",
    "market.eyebrow": "الكتالوج", "market.title": "المعرض", "market.intro": "قطعة موثقة اختارها خبراؤنا. ابحث فوراً وصفِّ حسب الخامة أو السعر.", "market.filters": "التصفية", "market.category": "الفئة", "market.allCategories": "كل الفئات", "market.material": "الخامة", "market.allMaterials": "كل الخامات", "market.maxPrice": "أقصى سعر", "market.reset": "إعادة ضبط", "market.search": "ابحث في التحف", "market.searchPlaceholder": "ابحث بالعنوان أو الخامة أو الوصف…", "market.sort": "الترتيب", "market.newest": "الأحدث أولاً", "market.oldest": "الأقدم أولاً", "market.priceAsc": "السعر: من الأقل", "market.priceDesc": "السعر: من الأعلى", "market.piece": "قطعة", "market.pieces": "قطع", "market.found": "متاحة", "market.empty": "لا توجد نتائج مطابقة", "market.emptyHint": "جرّب توسيع نطاق السعر أو مسح عوامل التصفية.", "market.previous": "السابق", "market.next": "التالي",
    "product.material": "الخامة", "product.size": "الأبعاد", "product.weight": "الوزن", "product.view": "عرض التفاصيل", "product.add": "أضف إلى السلة", "product.added": "تمت إضافته إلى سلتك", "product.unavailable": "هذه القطعة لم تعد متاحة", "product.unavailableHint": "ربما وجدت منزلاً جديداً. تصفح بقية المجموعة.", "product.back": "العودة إلى المعرض", "product.category": "الفئة", "product.year": "السنة", "product.condition": "الحالة", "product.availability": "التوفر", "product.inStock": "في المخزون", "product.seller": "البائع", "product.verified": "تاجر موثق. يرفق تقرير الحالة وملف المصدر مع كل عملية شراء.", "product.contactSeller": "تواصل مع البائع", "product.contactTitle": "تواصل مع البائع", "product.contactDescription": "ستصل رسالتك حول هذه القطعة مباشرة إلى فريق جاديس آرت.", "product.sent": "تم إرسال الرسالة — سيرد خبير خلال يوم عمل.",
    "newsletter.eyebrow": "رسالة جامع التحف", "newsletter.title": "كن أول من يكتشف مقتنياتنا الجديدة", "newsletter.body": "رسالة منتقاة كل شهر: قطع موثقة حديثاً، معاينات خاصة وملاحظات من خبراء الترميم.", "newsletter.email": "البريد الإلكتروني", "newsletter.join": "اشترك", "newsletter.joining": "جارٍ الاشتراك…",
    "footer.about": "معرض منتقى للتحف والتصاميم العتيقة والمقتنيات والقطع ذات التاريخ الجدير بالحفظ.", "footer.explore": "استكشف", "footer.aboutLink": "عن جاديس آرت", "footer.contact": "اتصل بنا والأسئلة", "footer.cart": "سلة التسوق", "footer.categories": "الفئات", "footer.gallery": "المعرض", "footer.rights": "جميع الحقوق محفوظة.",
    "about.eyebrow": "عن الدار", "about.intro": "وُجدت جاديس آرت لأن القطع الجميلة تستحق وصفاً دقيقاً، ولأن جامعي التحف يستحقون معرفة ما يقتنونه بالضبط.",
    "about.storyEyebrow": "قصتنا", "about.storyTitle": "من الورشة إلى المعرض", "about.story1": "بدأت الدار كورشة ترميم في حي لومَريه بباريس: ثلاث طاولات عمل، وخزانة شفط، وعدد غير معقول من عينات الورنيش. كان العملاء يسألون دائماً أين يجدون قطعاً بالمستوى نفسه، وكان الجواب الصادق أن السوق غامض في معظمه.", "about.story2": "لذلك أنشأنا المعرض الذي كنا نتمنى الشراء منه. تُفحص كل قطعة شخصياً، ويُحدد تاريخها، وتُصوَّر بإضاءة ثابتة، وتُعرض مع تقرير حالة لا يخفي شيئاً. اليوم توصل جاديس آرت الأثاث واللوحات والمجوهرات والعملات والخزف والنوادر إلى مجموعات في ثلاثين دولة.", "about.storyCta": "اطّلع على المتاح الآن", "about.storyImageAlt": "تمثال نصفي رخامي كلاسيكي في مرسم جاديس آرت",
    "about.missionTitle": "مهمتنا", "about.mission": "أن يصبح اقتناء التحفة واضحاً ومطمئناً كأي عملية شراء أخرى: أوصاف دقيقة، ومصدر موثق، وأسعار عادلة، وخبراء يردّون على الهاتف.", "about.visionTitle": "رؤيتنا", "about.vision": "سوق تنتقل فيه القطع التاريخية بمسؤولية — مدروسة جيداً، ومرمّمة بعناية، وتُسلَّم بحال أفضل مما وجدناها عليه.",
    "about.valuesEyebrow": "ما نلتزم به", "about.valuesTitle": "قيمنا", "about.value1.title": "الصدق قبل اللمعان", "about.value1.body": "نصوّر الشروخ بالعناية نفسها التي نصوّر بها التذهيب، ويذكر تقرير الحالة كل ترميم.", "about.value2.title": "البحث العلمي", "about.value2.body": "النسبة إلى صانعٍ بحثٌ لا تخمين. وإن لم نستطع إثباتها قلنا ذلك بوضوح.", "about.value3.title": "الرعاية", "about.value3.body": "نبيع لمن سيعتني بالقطعة، ونساعده على القيام بذلك على الوجه الصحيح.", "about.value4.title": "التعامل العادل", "about.value4.body": "أسعار شفافة للمشترين وشروط منصفة للتجار والحرفيين الذين نعمل معهم.",
    "about.trustEyebrow": "راحة البال", "about.trustTitle": "لماذا يثق بنا عملاؤنا", "about.trust1": "توثيق مستقل لكل قطعة قبل عرضها", "about.trust2": "تقرير حالة مكتوب وملف مصدر مع كل عملية بيع", "about.trust3": "إمكانية الإرجاع خلال 14 يوماً لأي قطعة تختلف عن وصفها", "about.trust4": "شحن مؤمَّن عالمياً في صناديق مخصصة للأعمال الفنية", "about.trust5": "خبراء متاحون عبر الهاتف أو البريد الإلكتروني أو بموعد خاص", "about.talk": "تحدث مع خبير",
    "account.label": "حسابي", "account.logout": "تسجيل الخروج", "account.profile": "الملف الشخصي", "account.orders": "الطلبات", "account.cart": "السلة", "account.wishlist": "المفضلة", "account.messages": "الرسائل", "account.profileInfo": "معلومات الملف الشخصي", "account.firstName": "الاسم الأول", "account.lastName": "اسم العائلة", "account.phone": "رقم الهاتف", "account.saving": "جارٍ الحفظ…", "account.save": "حفظ التغييرات", "account.updated": "تم تحديث الملف الشخصي.", "account.saveError": "تعذر حفظ ملفك الشخصي.", "account.noOrder": "لم تطلب أي شيء بعد.", "account.emptyCart": "سلتك فارغة.", "account.emptyWishlist": "قائمة المفضلة فارغة. استخدم رمز القلب لحفظ قطعة.", "account.remove": "إزالة", "account.total": "الإجمالي", "account.checkout": "إتمام الطلب", "account.order": "طلب", "account.browse": "اكتشف المجموعة",
    "auth.account": "حساب جاديس آرت", "auth.welcome": "مرحباً", "auth.intro": "تابع طلباتك ومفضلاتك ومحادثاتك مع خبرائنا.", "auth.signIn": "تسجيل الدخول", "auth.create": "إنشاء حساب", "auth.google": "المتابعة عبر Google", "auth.connecting": "جارٍ الاتصال…", "auth.or": "أو", "auth.password": "كلمة المرور", "auth.signingIn": "جارٍ تسجيل الدخول…", "auth.createMy": "إنشاء حسابي", "auth.creating": "جارٍ إنشاء الحساب…", "auth.help": "تحتاج إلى مساعدة؟", "auth.chat": "تحدث مع خدمة العملاء", "auth.googleError": "فشل تسجيل الدخول عبر Google. حاول مرة أخرى.", "auth.welcomeBack": "مرحباً بعودتك إلى جاديس آرت.", "auth.ready": "حسابك في جاديس آرت جاهز.", "auth.confirmEmail": "تحقق من بريدك لتأكيد عنوانك الإلكتروني.", "validation.firstName": "أدخل اسمك الأول", "validation.lastName": "أدخل اسم عائلتك", "validation.email": "أدخل عنوان بريد إلكتروني صحيحاً", "validation.phone": "أدخل رقم هاتفك", "validation.password": "استخدم 8 أحرف على الأقل",
    "cart.title": "سلة التسوق", "cart.empty": "سلة التسوق فارغة حالياً.", "cart.reserved": "قطعة محجوزة لك.", "cart.reservedPlural": "قطع محجوزة لك.", "cart.nothing": "لا شيء هنا بعد — تصفح المجموعة للعثور على قطعتك القادمة.", "cart.continue": "متابعة التسوق", "cart.decrease": "تقليل الكمية", "cart.increase": "زيادة الكمية", "cart.remove": "إزالة", "cart.summary": "ملخص الطلب", "cart.subtotal": "المجموع الفرعي", "cart.shipping": "الشحن", "cart.shippingQuote": "يُحدد بعد إتمام الطلب", "cart.proceed": "المتابعة إلى الدفع",
    "categories.eyebrow": "المجموعات", "categories.title": "تصفح حسب الفئة", "categories.intro": "يختار خبراؤنا كل فئة ويوثقونها، من أثاث القرن الثامن عشر إلى الساعات النادرة.", "categories.available": "متاحة", "categories.piece": "قطعة", "categories.pieces": "قطع",
    "checkout.title": "إتمام الطلب", "checkout.empty": "سلة التسوق فارغة.", "checkout.signIn": "سجل الدخول أو أنشئ حساباً", "checkout.signInHint": "لتأكيد طلبك ومتابعة تقدمه.", "checkout.delivery": "بيانات التسليم", "checkout.fullName": "الاسم الكامل", "checkout.address": "العنوان", "checkout.city": "المدينة", "checkout.postal": "الرمز البريدي", "checkout.country": "الدولة", "checkout.confirming": "جارٍ التأكيد…", "checkout.confirm": "تأكيد الطلب", "checkout.payment": "لا يتم تحصيل أي دفعة عبر الإنترنت. سيتواصل معك فريقنا برابط دفع آمن وعرض سعر للشحن.", "checkout.quantity": "الكمية", "checkout.confirmed": "تم تأكيد الطلب — سيتواصل فريقنا معك بشأن التسليم.", "checkout.signInRequired": "سجل الدخول لتأكيد طلبك.", "checkout.correctFields": "صحح الحقول المميزة.", "checkout.orderError": "تعذر إتمام طلبك. حاول مرة أخرى.", "checkout.itemsError": "تم إنشاء طلبك لكن تعذر حفظ القطع. يرجى التواصل معنا.",
    "contact.eyebrow": "تواصل معنا", "contact.title": "تواصل مع معرض جاديس آرت", "contact.intro": "لديك سؤال عن قطعة أو تقييم أو توصيل؟ يجيب خبراؤنا عن كل رسالة شخصياً.", "contact.email": "البريد الإلكتروني", "contact.phone": "الهاتف", "contact.address": "العنوان", "contact.hours": "ساعات العمل", "contact.send": "أرسل لنا رسالة", "contact.subject": "الموضوع", "contact.message": "الرسالة", "contact.sending": "جارٍ الإرسال…", "contact.sendButton": "إرسال الرسالة", "contact.inbox": "ستصل رسالتك إلى بريد جاديس آرت", "contact.help": "تحتاج إلى مساعدة؟", "contact.helpIntro": "فريق جاديس آرت متاح للإجابة عن أسئلتك.", "contact.contactUs": "تواصل معنا", "contact.chat": "تحدث مع خدمة العملاء", "contact.faq": "الأسئلة الشائعة", "contact.sent": "تم إرسال الرسالة — سيرد فريقنا خلال يوم عمل.", "contact.sendError": "تعذر إرسال رسالتك. حاول مرة أخرى.",
    "dashboard.seller": "منطقة البائع", "dashboard.title": "نشر تحفة", "dashboard.deniedTitle": "لوحة تحكم البائع", "dashboard.denied": "هذه المنطقة مخصصة لبائعي جاديس آرت. تواصل معنا إذا رغبت في عرض قطعك.", "dashboard.contact": "تواصل مع جاديس آرت", "dashboard.productTitle": "عنوان القطعة *", "dashboard.description": "الوصف *", "dashboard.images": "روابط الصور (رابط في كل سطر)", "dashboard.price": "السعر (يورو)", "dashboard.stock": "الكمية المتاحة", "dashboard.condition": "الحالة", "dashboard.sellerName": "اسم البائع", "dashboard.location": "موقع البائع", "dashboard.publishing": "جارٍ النشر…", "dashboard.publish": "نشر في المعرض", "dashboard.live": "الإعلانات المنشورة", "dashboard.published": "تم نشر الإعلان في المعرض.", "dashboard.publishError": "تعذر نشر الإعلان.",
    "support.eyebrow": "خدمة العملاء", "support.title": "تحتاج إلى مساعدة؟", "support.intro": "فريق جاديس آرت متاح للإجابة عن أسئلتك حول قطعة أو توصيل أو تقييم أو طلب حالي.", "support.email": "تواصل معنا عبر البريد", "support.contactForm": "نموذج التواصل", "chat.online": "متصل الآن", "chat.welcome": "مرحباً بك في جاديس آرت. اطرح سؤالك وسيرد فريقنا سريعاً.", "chat.you": "أنت", "chat.placeholder": "اكتب رسالتك…", "chat.send": "إرسال", "chat.login": "سجل الدخول", "chat.history": "للاحتفاظ بسجل محادثاتك.", "chat.open": "فتح دردشة خدمة العملاء", "chat.close": "إغلاق الدردشة", "newsletter.error": "تعذر حفظ اشتراكك. حاول مرة أخرى.", "newsletter.success": "مرحباً بك في دائرة جاديس آرت — ستصلك المقتنيات الجديدة أولاً.",
    "common.pageNotFound": "الصفحة غير موجودة", "common.pageMissing": "الصفحة التي تبحث عنها غير موجودة أو تم نقلها.", "common.goHome": "العودة للرئيسية", "common.pageError": "تعذر تحميل الصفحة", "common.pageErrorHint": "حدث خطأ من جانبنا. يمكنك تحديث الصفحة أو العودة إلى الرئيسية.", "common.tryAgain": "حاول مرة أخرى", "faq.1q": "كيف توثقون القطع التي تبيعونها؟", "faq.1a": "يفحص خبراؤنا كل قطعة، ويستعينون بخبير مستقل عند الحاجة. ويرافق كل عملية شراء تقرير حالة ومذكرة مصدر.", "faq.2q": "هل تشحنون دولياً؟", "faq.2a": "نعم. نتعاون مع شركات متخصصة في نقل الأعمال الفنية ونشحن إلى جميع أنحاء العالم مع تغليف متحفي وتأمين كامل.", "faq.3q": "هل يمكنني إرجاع قطعة؟", "faq.3a": "يمكنك إرجاع أي قطعة خلال 14 يوماً من التسليم إذا لم تطابق وصفها، على أن تعاد في صندوقها الأصلي.", "faq.4q": "هل تشترون التحف أو تقبلونها بنظام الأمانة؟", "faq.4a": "نعم. أرسل الصور والأبعاد وأي معلومات عن المصدر عبر النموذج، وسيرد فريق المقتنيات خلال يومي عمل.",
  },
} as const;

export const categoryLabels: Record<Language, Record<string, string>> = {
  en: { Furniture: "Furniture", Decorations: "Decorative Arts", Paintings: "Paintings", Sculptures: "Sculptures", Coins: "Coins", Jewelry: "Jewelry", Books: "Rare Books", Watches: "Watches", Ceramics: "Ceramics", Other: "Objects of Art" },
  fr: { Furniture: "Mobilier", Decorations: "Décoration", Paintings: "Peintures", Sculptures: "Sculptures", Coins: "Monnaies", Jewelry: "Bijoux", Books: "Livres rares", Watches: "Montres", Ceramics: "Céramiques", Other: "Objets d’art" },
  ar: { Furniture: "الأثاث", Decorations: "الديكور", Paintings: "اللوحات", Sculptures: "المنحوتات", Coins: "العملات", Jewelry: "المجوهرات", Books: "الكتب النادرة", Watches: "الساعات", Ceramics: "الخزف", Other: "التحف الفنية" },
};

type TranslationKey = keyof typeof translations.en;
type LanguageContextValue = { language: Language; setLanguage: (language: Language) => void; t: (key: TranslationKey) => string; categoryName: (category: string) => string };

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const saved = window.localStorage.getItem(STORAGE_KEY);
    if (saved === "en" || saved === "fr" || saved === "ar") setLanguageState(saved);
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
  }, [language]);

  const setLanguage = (next: Language) => {
    setLanguageState(next);
    window.localStorage.setItem(STORAGE_KEY, next);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t: (key) => translations[language][key] ?? translations.en[key], categoryName: (category) => categoryLabels[language][category] ?? category }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}